server:
  port: 9091
  
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testDB
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console/
      settings:
        web-allow-others: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
 msg: "Akash"